"""initial_dashboard

Revision ID: 1e0b298ed0ac
Revises:
Create Date: 2026-07-23 17:16:10.909793
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e0b298ed0ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('backtest_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('starting_bankroll', sa.Float(), nullable=False),
    sa.Column('min_bet', sa.Float(), nullable=False),
    sa.Column('windows_count', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_jobs_status'), 'backtest_jobs', ['status'], unique=False)
    op.create_table('bot_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_kind', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('guide_profile', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('session_budget', sa.Float(), nullable=False),
    sa.Column('min_bet', sa.Float(), nullable=False),
    sa.Column('once', sa.Boolean(), nullable=False),
    sa.Column('max_trades', sa.Integer(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('final_bankroll', sa.Float(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_runs_active', 'bot_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_bot_runs_status'), 'bot_runs', ['status'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_index(op.f('ix_worker_heartbeats_last_seen'), 'worker_heartbeats', ['last_seen'], unique=False)
    op.create_table('engine_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['bot_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_events_created_at'), 'engine_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_engine_events_event_type'), 'engine_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_engine_events_expires_at'), 'engine_events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_engine_events_run_id'), 'engine_events', ['run_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('window_ts', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('actual_outcome', sa.String(length=8), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('delta_pct', sa.Float(), nullable=False),
    sa.Column('bet', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('bankroll_after', sa.Float(), nullable=False),
    sa.Column('order_kind', sa.String(length=24), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('claim_required', sa.Boolean(), nullable=False),
    sa.Column('claim_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['bot_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_run_id'), 'trades', ['run_id'], unique=False)
    op.create_index('ix_trades_run_window', 'trades', ['run_id', 'window_ts'], unique=False)
    op.create_index(op.f('ix_trades_window_ts'), 'trades', ['window_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_window_ts'), table_name='trades')
    op.drop_index('ix_trades_run_window', table_name='trades')
    op.drop_index(op.f('ix_trades_run_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_engine_events_run_id'), table_name='engine_events')
    op.drop_index(op.f('ix_engine_events_expires_at'), table_name='engine_events')
    op.drop_index(op.f('ix_engine_events_event_type'), table_name='engine_events')
    op.drop_index(op.f('ix_engine_events_created_at'), table_name='engine_events')
    op.drop_table('engine_events')
    op.drop_index(op.f('ix_worker_heartbeats_last_seen'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_bot_runs_status'), table_name='bot_runs')
    op.drop_index('ix_bot_runs_active', table_name='bot_runs')
    op.drop_table('bot_runs')
    op.drop_index(op.f('ix_backtest_jobs_status'), table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
